version: "3.2"
services:
  opendj:
    build:
      context: opendj
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}_opendj
    restart: always
  keycloak_postgres:
    image: postgres:11.5-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_keycloak_postgres
    environment:
      - POSTGRES_DB=keycloak_postgres
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak_password
#    volumes:
#      - keycloak_vol_db_postgres:/var/lib/postgresql/data
    restart: always
  keycloak:
    image: jboss/keycloak:15.0.1
    container_name: ${COMPOSE_PROJECT_NAME}_keycloak
    volumes:
      - ./keycloak/demo.json:/tmp/demo.json
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=keycloak_postgres
      - DB_DATABASE=keycloak_postgres
      - PROXY_ADDRESS_FORWARDING=true
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak_password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - KEYCLOAK_IMPORT=/tmp/demo.json
      - KEYCLOAK_LOGLEVEL=DEBUG
    ports:
      - 15005:8080
    depends_on:
      - keycloak_postgres
    restart: always
  jupyter:
    container_name: ${COMPOSE_PROJECT_NAME}_jupyter
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    ports:
      - 15006:8888
    volumes:
      - ./notebooks:/notebooks
      - ./certs:/certs
  phppgadmin:
    container_name: ${COMPOSE_PROJECT_NAME}_phppgadmin
    image: bitnami/phppgadmin:latest
    ports:
      - 15007:8080
    links:
      - postgres:postgres
    environment:
      DATABASE_HOST: postgres
  phpldapadmin:
    container_name: ${COMPOSE_PROJECT_NAME}_phpldapadmin
    image: osixia/phpldapadmin:latest
    environment:
      PHPLDAPADMIN_HTTPS: "false"
      PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'opendj': [{'server': [{'tls': False}, {'port': 1389}]}, {'login': [{'bind_id': 'cn=Directory Manager'}]}]}]"
    ports:
      - 15008:80
    links:
      - opendj:opendj
